<a href="https://colab.research.google.com/github/Breezebrise/CS102UAT/blob/main/Week2_Assignment_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a NumPy program to reshape this 1D array [1 2 3 4 5 6] into a 2D array with 2 rows.

In [8]:
#2d array
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3) #variable names cannot contain spaces.
print("Reshape array")
print(reshaped_arr)

#The error message SyntaxError: invalid syntax in the cell with id JuREvIZ6-MTw indicates that there is a problem with how the code is written, specifically on the line reshaped arr = arr.reshape(2,3).

Reshape array
[[1 2 3]
 [4 5 6]]


Write a NumPy program to perform matrix multiplication between a 3x3 matrix and a 3x2 matrix

In [12]:
#define a 3x3 matrics
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
#define a 3x2 matrix
B = np.array([[10, 11],
              [12, 13],
              [14, 15]])
#perform matrix multiplication
C = np.dot(A, B)
print(C)
print("Matrix multiplication result:")
print(C)

[[ 76  82]
 [184 199]
 [292 316]]
Matrix multiplication result:
[[ 76  82]
 [184 199]
 [292 316]]


Write a NumPy program to find the most frequent value and the number of times it occured in the array


[

    [1, 2, 3, 2, 1],
    [4, 2, 5, 2, 6],
    [2, 1, 2, 3, 2],
    [7, 2, 8, 2, 9]  
 ]

In [13]:
#define the 2D array
arr = np.array([
    [1, 2, 3, 2, 1],
    [4, 2, 5, 2, 6],
    [2, 1, 2, 3, 2],
    [7, 2, 8, 2, 9]
])

#flatten the array to 1D
flat = arr.flatten()

#use np.bincount to count frequency
counts = np.bincount(flat)
most_frequent = np.argmax(counts)
frequency = counts[most_frequent]

print(f"Most frequent value: {most_frequent}")
print(f"Occurs {frequency} times")


Most frequent value: 2
Occurs 9 times


Given a NumPy array representing a dataset with missing values, write a program to replace all the missing values (NaNs) with the mean of the respective column.

[  [ 1.  2. nan  4.  5.],

 [ 6. nan  8.  9. 10.],

 [11. 12. 13. nan 15.],

 [16. 17. nan 19. 20.],

 [nan 22. 23. 24. 25.]  ]

In [15]:
import numpy as np
# Define the dataset with missing values (NaN)
data = np.array([
    [1., 2., np.nan, 4., 5.],
    [6., np.nan, 8., 9., 10.],
    [11., 12., 13., np.nan, 15.],
    [16., 17., np.nan, 19., 20.],
    [np.nan, 22., 23., 24., 25.]
])

# Step 1: Calculate the mean of each column, ignoring NaNs
column_means = np.nanmean(data, axis=0)

# Step 2: Replace NaNs with the corresponding column mean
# np.where creates a new array, replacing only where np.isnan(data) is True
cleaned_data = np.where(np.isnan(data), column_means, data)

# Print the cleaned array
print("Cleaned dataset with NaNs replaced by column means:")
print(cleaned_data)
#make sure data is properly filled and double check where np.nan goes if using it
###np.nan is a special constant in NumPy that represents "Not a Number", which is used for missing or undefined numeric data.
#nan by itself is not defined unless you specifically import it.


Cleaned dataset with NaNs replaced by column means:
[[ 1.          2.         14.66666667  4.          5.        ]
 [ 6.         13.25        8.          9.         10.        ]
 [11.         12.         13.         14.         15.        ]
 [16.         17.         14.66666667 19.         20.        ]
 [ 8.5        22.         23.         24.         25.        ]]


Write a program that takes a NumPy array representing a dataset with a column of dates and create a new column extracting the month of each date.

np.array([

    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
]

In [17]:
import numpy as np

#create the structured array with column types
data = np.array([
    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
], dtype=[('date', 'U10'), ('value1', 'i4'), ('value2', 'i4')])

#step 1: Extract the date column as strings
date_column = data['date']

#step 2: Convert the strings to numpy datetime64 objects
date_objects = np.array(date_column, dtype='datetime64[D]')

#step 3: Extract the month as integers from the datetime objects
months = np.array([d.astype('datetime64[M]').astype(str)[5:] for d in date_objects])

#step 4: Combine the original data with the month column
#stack horizontally using np.column_stack
final_data = np.column_stack((date_column, months, data['value1'], data['value2']))

#Show the final output with the month column added
print("Dataset with Month Column Extracted:")
print(final_data)


Dataset with Month Column Extracted:
[['2024-01-15' '01' '10' '100']
 ['2024-02-28' '02' '15' '150']
 ['2024-03-10' '03' '20' '200']
 ['2024-04-22' '04' '25' '250']
 ['2024-05-05' '05' '30' '300']
 ['2024-06-18' '06' '35' '350']
 ['2024-07-30' '07' '40' '400']
 ['2024-08-12' '08' '45' '450']
 ['2024-09-25' '09' '50' '500']
 ['2024-10-07' '10' '55' '550']]
